<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories']					= '카테고리';
$lang['error_must_select']			= 'You must select a category to organize';
$lang['error_not_found']			= '요청한 카테고리를 찾을 수 없습니다.';
$lang['organize_category']			= '"%s" 카테고리 구성하기';
$lang['organize']					= '구성하기';
$lang['category_id']				= 'ID';
$lang['category_form']				= '카테고리 정보';
$lang['name']						= '이름';
$lang['slug']						= 'Slug';
$lang['description']				= '설명';
$lang['excerpt']					= '요약 설명';
$lang['sequence']					= '순서';
$lang['image']						= '이미지';
$lang['seo_title']					= 'SEO 제목';
$lang['meta']						= '메타 데이타';
$lang['message_category_saved']		= '카테고리가 저장되었습니다!';
$lang['error_file_upload']			= '<p>업로드할 파일을 선택하지 않았습니다.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= '카테고리가 삭제되었습니다.';
$lang['current_file']				= '현재 파일';
$lang['confirm_delete_category']	= '이 카테고리를 삭제하시겠습니까?';
$lang['add_new_category']			= '카테고리 추가';
$lang['top_level_category']         = '최상위 카테고리';
$lang['no_categories']				= '현재 등록된 카테고리가 없습니다.';
$lang['attributes']					= '속성';
$lang['seo']						= 'SEO';
$lang['parent']						= '상위 카테고리';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop']				= '상품을 드래그하여 노출 순서를 바꾸세요.';
$lang['sku']						= 'SKU';
$lang['price']						= '가격';
$lang['sale']						= '판매';
$lang['max_file_size']				= '최대 파일 크기';
